/*
 * JS for AvatarMain generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '73f2c96b-81d5-4df0-b877-90c47a41c6b9';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "AvatarMain",
    "location": "AvatarMain.html"
}, {
    "name": "ResortPage",
    "location": "ResortPage.html"
}];

function AvatarMain_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'AvatarMain_mobilebutton_2',
        'mobileimage_19': 'AvatarMain_mobileimage_19',
        'panelNavListAvatar': 'AvatarMain_panelNavListAvatar',
        'mobilelistitem_5': 'AvatarMain_mobilelistitem_5',
        'mobilelistitembutton_6': 'AvatarMain_mobilelistitembutton_6',
        'mobilelistitem_7': 'AvatarMain_mobilelistitem_7',
        'mobilelistitembutton_8': 'AvatarMain_mobilelistitembutton_8',
        'mobilelistitem_9': 'AvatarMain_mobilelistitem_9',
        'mobilelistitembutton_10': 'AvatarMain_mobilelistitembutton_10',
        'mobilelistitem_11': 'AvatarMain_mobilelistitem_11',
        'mobilelistitembutton_12': 'AvatarMain_mobilelistitembutton_12',
        'mobilelistitem_13': 'AvatarMain_mobilelistitem_13',
        'mobilelistitembutton_14': 'AvatarMain_mobilelistitembutton_14',
        'mobilelistitem_15': 'AvatarMain_mobilelistitem_15',
        'mobilelistitembutton_16': 'AvatarMain_mobilelistitembutton_16',
        'mobilelistitem_17': 'AvatarMain_mobilelistitem_17',
        'mobilelistitembutton_18': 'AvatarMain_mobilelistitembutton_18'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'AvatarMain';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var AvatarMain_onLoad = function() {
            AvatarMain_elementsExtraJS();

            AvatarMain_deviceEvents();
            AvatarMain_windowEvents();
            AvatarMain_elementsEvents();
        };

    // screen window events


    function AvatarMain_windowEvents() {

        $('#AvatarMain').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function AvatarMain_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function AvatarMain_elementsExtraJS() {
        // screen (AvatarMain) extra code

        /* panelNavListAvatar */

        listView = $("#AvatarMain_panelNavListAvatar");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#AvatarMain_panelNavListAvatar .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_5 */

        /* mobilelistitem_7 */

        /* mobilelistitem_9 */

        /* mobilelistitem_11 */

        /* mobilelistitem_13 */

        /* mobilelistitem_15 */

        /* mobilelistitem_17 */

    };

    // screen elements handler


    function AvatarMain_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#AvatarMain_mobileheader [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio("leftMenuAvatar").panel("close");
                    $('[id="AvatarMain_leftMenuAvatar"]').panel("open");

                }
            },
        }, '#AvatarMain_mobileheader [name="mobilebutton_2"]');

        $(document).off("click", '[name="mobilelistitem_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        transition: 'fade',
                        reverse: false
                    });

                }
            },
        }, '[name="mobilelistitem_5"]');

        $(document).off("click", '[name="mobilelistitem_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('AvatarMain', {
                        transition: 'fade',
                        reverse: false
                    });

                }
            },
        }, '[name="mobilelistitem_7"]');

        $(document).off("click", '[name="mobilelistitem_13"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ResortPage', {
                        transition: 'fade',
                        reverse: false
                    });

                }
            },
        }, '[name="mobilelistitem_13"]');

    };

    $(document).off("pagebeforeshow", "#AvatarMain").on("pagebeforeshow", "#AvatarMain", function(event, ui) {
        Apperyio.CurrentScreen = "AvatarMain";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    AvatarMain_onLoad();
};

$(document).off("pagecreate", "#AvatarMain").on("pagecreate", "#AvatarMain", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    AvatarMain_js();
});