/*
 * JS for ResortPage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '73f2c96b-81d5-4df0-b877-90c47a41c6b9';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "AvatarMain",
    "location": "AvatarMain.html"
}, {
    "name": "ResortPage",
    "location": "ResortPage.html"
}];

function ResortPage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'ResortPage_mobilebutton_2',
        'mobilelist_4': 'ResortPage_mobilelist_4',
        'mobilelistitem_5': 'ResortPage_mobilelistitem_5',
        'mobilelistitembutton_6': 'ResortPage_mobilelistitembutton_6',
        'mobilelistitem_7': 'ResortPage_mobilelistitem_7',
        'mobilelistitembutton_8': 'ResortPage_mobilelistitembutton_8',
        'mobilelistitem_9': 'ResortPage_mobilelistitem_9',
        'mobilelistitembutton_10': 'ResortPage_mobilelistitembutton_10',
        'mobilelistitem_11': 'ResortPage_mobilelistitem_11',
        'mobilelistitembutton_12': 'ResortPage_mobilelistitembutton_12',
        'mobilelistitem_13': 'ResortPage_mobilelistitem_13',
        'mobilelistitembutton_14': 'ResortPage_mobilelistitembutton_14',
        'mobilelistitem_15': 'ResortPage_mobilelistitem_15',
        'mobilelistitembutton_16': 'ResortPage_mobilelistitembutton_16',
        'mobilelistitem_17': 'ResortPage_mobilelistitem_17',
        'mobilelistitembutton_18': 'ResortPage_mobilelistitembutton_18'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'ResortPage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var ResortPage_onLoad = function() {
            ResortPage_elementsExtraJS();

            ResortPage_deviceEvents();
            ResortPage_windowEvents();
            ResortPage_elementsEvents();
        };

    // screen window events


    function ResortPage_windowEvents() {

        $('#ResortPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function ResortPage_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function ResortPage_elementsExtraJS() {
        // screen (ResortPage) extra code

        /* mobilelist_4 */

        listView = $("#ResortPage_mobilelist_4");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#ResortPage_mobilelist_4 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_5 */

        /* mobilelistitem_7 */

        /* mobilelistitem_9 */

        /* mobilelistitem_11 */

        /* mobilelistitem_13 */

        /* mobilelistitem_15 */

        /* mobilelistitem_17 */

    };

    // screen elements handler


    function ResortPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#ResortPage_mobileheader [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio("panel_3").panel("close");
                    $('[id="ResortPage_panel_3"]').panel("open");

                }
            },
        }, '#ResortPage_mobileheader [name="mobilebutton_2"]');

        $(document).off("click", '[name="mobilelistitem_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        transition: 'fade',
                        reverse: false
                    });

                }
            },
        }, '[name="mobilelistitem_5"]');

        $(document).off("click", '[name="mobilelistitem_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('AvatarMain', {
                        transition: 'fade',
                        reverse: false
                    });

                }
            },
        }, '[name="mobilelistitem_7"]');

        $(document).off("click", '[name="mobilelistitem_13"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ResortPage', {
                        transition: 'fade',
                        reverse: false
                    });

                }
            },
        }, '[name="mobilelistitem_13"]');

    };

    $(document).off("pagebeforeshow", "#ResortPage").on("pagebeforeshow", "#ResortPage", function(event, ui) {
        Apperyio.CurrentScreen = "ResortPage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    ResortPage_onLoad();
};

$(document).off("pagecreate", "#ResortPage").on("pagecreate", "#ResortPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    ResortPage_js();
});