/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '73f2c96b-81d5-4df0-b877-90c47a41c6b9';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "AvatarMain",
    "location": "AvatarMain.html"
}, {
    "name": "ResortPage",
    "location": "ResortPage.html"
}];

function startScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_6': 'startScreen_mobilebutton_6',
        'mobilegrid_25': 'startScreen_mobilegrid_25',
        'mobilegridcell_26': 'startScreen_mobilegridcell_26',
        'mobilegrid_31': 'startScreen_mobilegrid_31',
        'mobilegridcell_32': 'startScreen_mobilegridcell_32',
        'mobiletextarea_39': 'startScreen_mobiletextarea_39',
        'mobilegridcell_34': 'startScreen_mobilegridcell_34',
        'mobiletextarea_40': 'startScreen_mobiletextarea_40',
        'mobilegridcell_36': 'startScreen_mobilegridcell_36',
        'mobiletextarea_41': 'startScreen_mobiletextarea_41',
        'mobilegridcell_37': 'startScreen_mobilegridcell_37',
        'mobiletextarea_42': 'startScreen_mobiletextarea_42',
        'mobilegridcell_38': 'startScreen_mobilegridcell_38',
        'mobiletextarea_43': 'startScreen_mobiletextarea_43',
        'mobilegridcell_27': 'startScreen_mobilegridcell_27',
        'mobileimage_30': 'startScreen_mobileimage_30',
        'panelNavListMain': 'startScreen_panelNavListMain',
        'mobilelistitem_9': 'startScreen_mobilelistitem_9',
        'mobilelistitembutton_10': 'startScreen_mobilelistitembutton_10',
        'mobilelistitem_11': 'startScreen_mobilelistitem_11',
        'mobilelistitembutton_12': 'startScreen_mobilelistitembutton_12',
        'mobilelistitem_13': 'startScreen_mobilelistitem_13',
        'mobilelistitembutton_14': 'startScreen_mobilelistitembutton_14',
        'mobilelistitem_15': 'startScreen_mobilelistitem_15',
        'mobilelistitembutton_16': 'startScreen_mobilelistitembutton_16',
        'mobilelistitem_17': 'startScreen_mobilelistitem_17',
        'mobilelistitembutton_18': 'startScreen_mobilelistitembutton_18',
        'mobilelistitem_19': 'startScreen_mobilelistitem_19',
        'mobilelistitembutton_20': 'startScreen_mobilelistitembutton_20',
        'mobilelistitem_21': 'startScreen_mobilelistitem_21',
        'mobilelistitembutton_22': 'startScreen_mobilelistitembutton_22'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["startScreen_restservice1_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {

            "to_name": "restservice1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["startScreen_restservice1_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": []
    };

    Apperyio.mappings["startScreen_restservice2_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {

            "to_name": "restservice2",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["startScreen_restservice2_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": []
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.restservice1 = Apperyio.datasources.restservice1 = new Apperyio.DataSource(WarehouseDB_Merchandise_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_restservice1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_restservice1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.restservice2 = Apperyio.datasources.restservice2 = new Apperyio.DataSource(VistaTestOneDB_VistaTestOneCollection_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_restservice2_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_restservice2_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events


    function startScreen_windowEvents() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#startScreen').on({
            pageshow: function(event) {
                try {
                    restservice2.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        });

    };

    // device events


    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code

        /* panelNavListMain */

        listView = $("#startScreen_panelNavListMain");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#startScreen_panelNavListMain .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_9 */

        /* mobilelistitem_11 */

        /* mobilelistitem_13 */

        /* mobilelistitem_15 */

        /* mobilelistitem_17 */

        /* mobilelistitem_19 */

        /* mobilelistitem_21 */

    };

    // screen elements handler


    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#startScreen_mobileheader1 [name="mobilebutton_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio("mainLeftMenu").panel("close");
                    $('[id="startScreen_mainLeftMenu"]').panel("open");

                }
            },
        }, '#startScreen_mobileheader1 [name="mobilebutton_6"]');

        $(document).off("click", '[name="mobilelistitem_9"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        transition: 'fade',
                        reverse: false
                    });

                }
            },
        }, '[name="mobilelistitem_9"]');

        $(document).off("click", '[name="mobilelistitem_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('AvatarMain', {
                        transition: 'fade',
                        reverse: false
                    });

                }
            },
        }, '[name="mobilelistitem_11"]');

        $(document).off("click", '[name="mobilelistitem_17"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ResortPage', {
                        transition: 'fade',
                        reverse: false
                    });

                }
            },
        }, '[name="mobilelistitem_17"]');

    };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    startScreen_onLoad();
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});